services:
  00-web:
    container_name: elector.backend
    image: ${DOCKER_REGISTRY-}00web
    build:
      context: .
      dockerfile: src/Backend/00-Web/Dockerfile
      args:
        - CONFIGURATION=${CONFIGURATION:-Debug}
    env_file:
      - "variables.dev.env"
    ports:
      - "44210:44210"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      elector.database.init:
        condition: service_completed_successfully
     # elector.database:
     #   condition: service_healthy
      elector.jaeger:
        condition: service_started

  elector.jaeger:
    container_name: elector.jaeger
    image: jaegertracing/all-in-one:1.58
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://localhost:43000
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=${PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR:-true}
      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT:-}
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    ports:
      - '41100:16686'
      - '4317:4317'
      - '4318:4318'

  elector.database:
    container_name: 'elector.database'
    image: 'mcr.microsoft.com/mssql/server:2025-CU2-ubuntu-22.04'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pce@Elector26
      - MSSQL_PID=Developer
    ports:
      - 43100:1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -No -S localhost -U sa -P "Pce@Elector26" -d 'master' -Q 'selct 1'
      interval: 5s
      timeout: 5s
      retries: 10

  elector.database.init:
    container_name: elector.database.init
    image: 'mcr.microsoft.com/mssql/server:2025-CU2-ubuntu-22.04'
    volumes:
      - ../dbinit:/docker-entrypoint-initdb.d
    depends_on:
      elector.database:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -No -S elector.database -U sa -P Pce@Elector26 -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '

