namespace Application.Models.Errors;

public enum ValidationErrorCode
{
    Required = 0,
    MaxLength,
    MinLength,
    Unique,
    Base64Format,
    InvalidPassword,
    PositiveNumber,
    GreaterThanZero,
    DocumentMustExist,
    UserMustExist,
    RoleMustExist,
    UserLinked,
    UserCannotBeCurrentUser,
    InvalidNameFromParent,
    InvalidEmail,
    InvalidEnum,
    InvalidLevel,
    InvalidDate,
    InvalidBirthDate,
    ConstituencyMustExist,
    InvalidSearchTerm,
    DefaultRoleCannotBeAltered,
    InvalidParent,
    MarriedNameRequired,
    ConstituencyMustHaveParent,
    AlreadyExists,
    AlreadyRegisteredAsElector,
    PollingStationMustExist,
    TooManyAttachments,
}
